### ISSUE TITLE
No way to specify the queue with Verdict::Queue

### ISSUE THREAD

**Issue by vorner** [chifflier/nfqueue-rs#12]
As the documentation says [here](https://docs.rs/nfqueue/0.9.1/nfqueue/enum.Verdict.html), the target queue to put the packet into with the Queue verdict is encoded by putting it into the 16 high bits of the verdict. This is likely copied from the C version where it is reasonably possible to combine the value (`VERDICT_QUEUE | (queue << 16)`). This is *not* possible in Rust ‒ doing that would create a non-existent variant of the `Verdict` enum, which is UB in Rust (and one would likely need to use something like transmute to do that anyway).

**Comment by chifflier** [comment]
Fixed by f716803
