### ISSUE TITLE
[IMP] `libnetfilter-queue` binding script ?

### ISSUE THREAD

**Issue by LuoZijun** [chifflier/nfqueue-rs#9]
hi, i got some question:

*  the `libnetfilter-queue`  shuld have one build script (`build.rs`) ? 
*  i can't see any headers file about `libnetfilter-queue` .
* package [pnet](https://github.com/chifflier/nfqueue-rs/blob/master/Cargo.toml#L16) never used.

thx!

**Comment by chifflier** [comment]
Hi,
Here are a few answers (sorry for the delay)
- why would it need a `build.rs` file ?
- there should be no need to include the header, the goal of this crate is not to expose the low-level functions, but an abstraction
- `pnet` usage has been moved to dev-dependencies, to be able to build the examples (which use it)
